import type { ShopProduct } from '@/components/shop/types';

export const ALL_PRODUCTS: ShopProduct[] = [
  {
    id: 'loving-you-frozen',
    name: 'Loving You Frozen',
    scentFamily: 'Floral · Musky',
    scentTags: ['Floral'],
    price: 149500,
    image: '/images/image5.jpeg',
    badge: 'Best Seller',
    href: '/shop/loving-you-frozen',
    rating: 4.8,
    reviewCount: 142,
    gender: 'Her',
    sizes: ['30ml', '50ml', '100ml'],
    createdAt: 1700000000,
  },
  {
    id: 'stronger-for-you-intense',
    name: 'Stronger For You Intense',
    scentFamily: 'Woody · Spicy',
    scentTags: ['Woody'],
    price: 175000,
    image: '/images/image3.jpeg',
    href: '/shop/stronger-for-you-intense',
    rating: 4.5,
    reviewCount: 89,
    gender: 'Him',
    sizes: ['50ml', '100ml'],
    createdAt: 1705000000,
  },
  {
    id: 'stronger-for-you-absolute',
    name: 'Stronger For You Absolute',
    scentFamily: 'Oriental · Resinous',
    scentTags: ['Oriental'],
    price: 185000,
    image: '/images/image11.jpeg',
    badge: 'New',
    href: '/shop/stronger-for-you-absolute',
    rating: 4.7,
    reviewCount: 34,
    gender: 'Him',
    sizes: ['50ml', '100ml'],
    createdAt: 1711000000,
  },
  {
    id: 'suger-edp',
    name: 'Suger EDP',
    scentFamily: 'Fresh · Green',
    scentTags: ['Fresh'],
    price: 139500,
    image: '/images/image1.jpeg',
    href: '/shop/suger-edp',
    rating: 4.2,
    reviewCount: 61,
    gender: 'Unisex',
    sizes: ['30ml', '50ml'],
    createdAt: 1698000000,
  },
  {
    id: 'oud-imperiale',
    name: 'Oud Impériale',
    scentFamily: 'Oud · Oriental',
    scentTags: ['Oriental'],
    price: 235000,
    image: '/images/image8.jpeg',
    badge: 'New',
    href: '/shop/oud-imperiale',
    rating: 4.9,
    reviewCount: 22,
    gender: 'Unisex',
    sizes: ['15ml', '50ml', '100ml'],
    createdAt: 1712000000,
  },
  {
    id: 'aurore-blanche',
    name: 'Aurore Blanche',
    scentFamily: 'White Musk · Floral',
    scentTags: ['Floral', 'Fresh'],
    price: 132000,
    image: '/images/image7.jpeg',
    badge: 'New',
    href: '/shop/aurore-blanche',
    rating: 4.6,
    reviewCount: 18,
    gender: 'Her',
    sizes: ['15ml', '50ml', '100ml'],
    createdAt: 1712500000,
  },
  {
    id: 'vetiver-noir',
    name: 'Vétiver Noir',
    scentFamily: 'Woody · Smoky',
    scentTags: ['Woody'],
    price: 138000,
    image: '/images/image11.jpeg',
    badge: 'New',
    href: '/shop/vetiver-noir',
    rating: 4.4,
    reviewCount: 15,
    gender: 'Him',
    sizes: ['15ml', '50ml', '100ml'],
    createdAt: 1712800000,
  },
  {
    id: 'citrus-bloom',
    name: 'Citrus Bloom',
    scentFamily: 'Citrus · Fresh',
    scentTags: ['Citrus', 'Fresh'],
    price: 98000,
    image: '/images/image2.jpeg',
    href: '/shop/citrus-bloom',
    rating: 4.1,
    reviewCount: 47,
    gender: 'Unisex',
    sizes: ['30ml', '50ml'],
    createdAt: 1695000000,
  },
  {
    id: 'rose-oud',
    name: 'Rose Oud',
    scentFamily: 'Floral · Oriental',
    scentTags: ['Floral', 'Oriental'],
    price: 195000,
    image: '/images/image4.jpeg',
    badge: 'Low Stock',
    href: '/shop/rose-oud',
    rating: 4.7,
    reviewCount: 73,
    gender: 'Her',
    sizes: ['50ml', '100ml'],
    createdAt: 1702000000,
  },
  {
    id: 'cedar-dusk',
    name: 'Cedar Dusk',
    scentFamily: 'Woody · Earthy',
    scentTags: ['Woody'],
    price: 115000,
    image: '/images/image9.jpeg',
    href: '/shop/cedar-dusk',
    rating: 4.3,
    reviewCount: 38,
    gender: 'Him',
    sizes: ['30ml', '50ml', '100ml'],
    createdAt: 1699000000,
  },
  {
    id: 'petite-fleur',
    name: 'Petite Fleur',
    scentFamily: 'Floral · Powdery',
    scentTags: ['Floral'],
    price: 88000,
    image: '/images/image6.jpeg',
    badge: 'Low Stock',
    href: '/shop/petite-fleur',
    rating: 4.0,
    reviewCount: 29,
    gender: 'Her',
    sizes: ['15ml', '30ml'],
    createdAt: 1696000000,
  },
  {
    id: 'amber-noir',
    name: 'Amber Noir',
    scentFamily: 'Oriental · Amber',
    scentTags: ['Oriental'],
    price: 162000,
    image: '/images/image10.jpeg',
    href: '/shop/amber-noir',
    rating: 4.5,
    reviewCount: 56,
    gender: 'Unisex',
    sizes: ['50ml', '100ml'],
    createdAt: 1701000000,
  },
];

export const PRODUCT_MAP = new Map(ALL_PRODUCTS.map(p => [p.id, p]));
